name: 🦠 Баг-репорт
description: Если что-то работает не так.
labels: ["Баг", "Нужна проверка"]
body:
  - type: markdown
    attributes:
      value:
        - Баг-репорты нужны для сообщения о неправильно работающих вещах. Предложения находятся в [другом разделе](https://github.com/octothorp-team/public-dobrograd/discussions)
        - Каждая ошибка должна быть в отдельном репорте, не стоит создавать списки, если только эта совокупность ошибок не в одной области.
  - type: textarea
    id: what-happened
    attributes:
      label: Что наблюдается?
      description: Опиши подробно, что именно происходит на момент написания репорта
      placeholder: Кнопка не нажимается, ничего не происходит...
    validations:
      required: true
  - type: textarea
    id: correct-behaviour
    attributes:
      label: Как это должно работать?
      description: Как, по твоему мнению, это должно работать, что нужно изменить
      placeholder: В шкафу уборщицы должна быть форма горничной....
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: Как это повторить?
      description: Пошагово опиши, как повторить эту ошибку
      placeholder: 1) Засунуть клоуна туда... 2) Попытаться взломать...
    validations:
      required: false
  - type: input
    id: contact
    attributes:
      label: Обратная связь
      description: Если нам понадобится что-то уточнить, как с тобой связаться?
      placeholder: "например, Discord: human#0000"
    validations:
      required: false
