name: 💡 Идея
description: Если хочешь что-то добавить
labels: ["Нужна проверка"]
body:
  - type: markdown
    attributes:
      value:
        - Каждая идея должна быть в отдельном репорте, не стоит создавать списки, если только эта совокупность ошибок не в одной области.
        - Рофловые идея будут сразу отклоняться.
  - type: textarea
    id: some-idea
    attributes:
      label: В чём суть идеи?
      description: Опиши подробно, что ты хочешь добавить
      placeholder: Надо добавить печать Командиру Экспедиции...
    validations:
      required: true
  - type: textarea
    id: why-idea
    attributes:
      label: Почему эта идея должна быть принята?
      description: Объясни, зачем твоя идея должна быть принята командой разработчиков
      placeholder: Потому что Командир Экспедиции - глава отдела...
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Обратная связь
      description: Если нам понадобится что-то уточнить, как с тобой связаться?
      placeholder: "например, Discord: human#0000"
    validations:
      required: false
