name: 💡 Запрос
description: ТОЛЬКО ДЛЯ ВЕДУЩИХ РАЗРАБОТЧИКОВ (778b, руководство)
labels: []
body:
  - type: markdown
    attributes:
      value:
        - Данная форма **ИСКЛЮЧИТЕЛЬНО** для ведущих разработчиков. (778b, руководство)
  - type: textarea
    id: short-request
    attributes:
      label: Кратко
      description: Кратко назовите суть запроса
      placeholder: Переместите прототипы...
    validations:
      required: true
  - type: textarea
    id: long-idea
    attributes:
      label: Почему эта идея должна быть принята?
      description: Объясни, зачем твоя идея должна быть принята командой разработчиков
      placeholder: Переместить прототипы в папку /Audio/Ramiles/...
    validations:
      required: false
  - type: input
    id: contact
    attributes:
      label: Обратная связь
      description: Если нам понадобится что-то уточнить, как с тобой связаться?
      placeholder: "например, Discord: human#0000"
    validations:
      required: false
