- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Aspid
  - Bagel
  - Barratry
  - Cluster
<<<<<<< HEAD
  - Fland
  - Kettle
  - Marathon
  - Meta
  - Moose
  - Omega
  - Origin
  - Saltern
=======
  - Moose
  - Omega
  - Eclipse
  
>>>>>>> master
